"""add: [comments] comment and reaction models

Revision ID: cfe8962e5198
Revises: bc8dad771541
Create Date: 2026-06-05 10:19:51.045727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfe8962e5198'
down_revision = 'bc8dad771541'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('read_only', sa.Boolean(), nullable=True),
    sa.Column('protected', sa.Boolean(), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('api_key', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('force_logout', sa.Boolean(), nullable=False),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('verification_token', sa.String(length=8), nullable=True),
    sa.Column('verification_expires_at', sa.DateTime(), nullable=True),
    sa.Column('pending_email', sa.String(length=128), nullable=True),
    sa.Column('pending_email_token', sa.String(length=8), nullable=True),
    sa.Column('pending_email_expires_at', sa.DateTime(), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('avatar_filename', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('job_title', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=200), nullable=True),
    sa.Column('social_twitter', sa.String(length=50), nullable=True),
    sa.Column('social_github', sa.String(length=50), nullable=True),
    sa.Column('social_linkedin', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_api_key'), ['api_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role_id'), ['role_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('comment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_original', sa.Text(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('root_id', sa.Integer(), nullable=True),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('object_id', sa.Integer(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_object_id'), ['object_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_object_type'), ['object_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_parent_id'), ['parent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_root_id'), ['root_id'], unique=False)

    op.create_table('log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('object_id', sa.String(length=36), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_level'), ['level'], unique=False)

    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission')
    )
    op.create_table('site_config',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=256), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('comment_reaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reaction', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='uq_comment_reaction_user')
    )
    with op.batch_alter_table('comment_reaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comment_reaction_comment_id'), ['comment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comment_reaction_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('user_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('toast_position', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('toast_style', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('toast_duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_config', schema=None) as batch_op:
        batch_op.drop_column('toast_duration')
        batch_op.drop_column('toast_style')
        batch_op.drop_column('toast_position')

    with op.batch_alter_table('comment_reaction', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_reaction_user_id'))
        batch_op.drop_index(batch_op.f('ix_comment_reaction_comment_id'))

    op.drop_table('comment_reaction')
    op.drop_table('site_config')
    op.drop_table('role_permission')
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_level'))
        batch_op.drop_index(batch_op.f('ix_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_log_category'))
        batch_op.drop_index(batch_op.f('ix_log_actor_id'))
        batch_op.drop_index(batch_op.f('ix_log_action'))

    op.drop_table('log')
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comment_root_id'))
        batch_op.drop_index(batch_op.f('ix_comment_parent_id'))
        batch_op.drop_index(batch_op.f('ix_comment_object_type'))
        batch_op.drop_index(batch_op.f('ix_comment_object_id'))
        batch_op.drop_index(batch_op.f('ix_comment_created_by'))

    op.drop_table('comment')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_role_id'))
        batch_op.drop_index(batch_op.f('ix_user_last_name'))
        batch_op.drop_index(batch_op.f('ix_user_first_name'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_api_key'))

    op.drop_table('user')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_name'))

    op.drop_table('role')
    # ### end Alembic commands ###
